package main

import (
	"bytes"
	"encoding/binary"
	"encoding/gob"
	"fmt"
	"log"
	"os"

	"github.com/Pietot/Gonnect-4/database"
	"go.etcd.io/bbolt"
)

const (
	ASCII_OFFSET = 65
)

func main() {
	db, err := bbolt.Open("../database/gonnect4_book.db", 0o600, &bbolt.Options{ReadOnly: true})
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	f, err := os.Create("../database/map.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "package database")
	fmt.Fprintln(f, "\n// Code generated by go generate - DO NOT MODIFY")
	for i := int8(-18); i <= 18; i++ {
		fmt.Fprintf(f, "var %s int8 = %d\n", indexToLetters(&i), i)
	}
	fmt.Fprintln(f, "var ExportedBook = map[uint64][7]*int8{")

	err = db.View(func(tx *bbolt.Tx) error {
		b := tx.Bucket([]byte(database.BucketResults))
		if b == nil {
			return fmt.Errorf("the bucket results does not exist")
		}

		return b.ForEach(func(k, v []byte) error {
			key := binary.BigEndian.Uint64(k)

			var scores [7]*int8
			buf := bytes.NewBuffer(v)
			if err := gob.NewDecoder(buf).Decode(&scores); err != nil {
				return err
			}

			fmt.Fprintf(f, "\t%d: {", key)
			for i, s := range scores {
				if *s == -128 {
					fmt.Fprint(f, "nil")
				} else {
					fmt.Fprintf(f, "&%s", indexToLetters(s))
				}
				if i < 6 {
					fmt.Fprint(f, ", ")
				}
			}
			fmt.Fprintln(f, "},")
			return nil
		})
	})

	if err != nil {
		log.Fatal(err)
	}

	fmt.Fprintln(f, "}")
}

func indexToLetters(n *int8) string {
	if *n < -18 || *n > 18 {
		panic("n must be between -18 and 18")
	}
	// Shift n to be between 0 and 36
	shifted := *n + 18

	first := shifted / 26
	second := shifted % 26

	return string(rune('a'+first)) + string(rune('a'+second))
}
