package main

import (
	"bytes"
	"encoding/binary"
	"encoding/gob"
	"fmt"
	"log"
	"os"

	"github.com/Pietot/Gonnect-4/database"
	"github.com/dgraph-io/badger/v4"
)

func main() {
	opts := badger.DefaultOptions(config.DEFAULT_DB_PATH)
	opts.Logger = nil
	db, err := badger.Open(opts)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	f, err := os.Create("../database/map.go")
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	fmt.Fprintln(f, "package database")
	fmt.Fprintln(f, "\n// Code generated by go generate - DO NOT MODIFY")
	fmt.Fprintln(f, "var ExportedBook = map[uint64][7]int8{")

	err = db.View(func(txn *badger.Txn) error {
		opts := badger.DefaultIteratorOptions
		opts.Prefix = database.PrefixResults
		it := txn.NewIterator(opts)
		defer it.Close()

		for it.Rewind(); it.Valid(); it.Next() {
			item := it.Item()
			k := item.KeyCopy(nil)
			v, err := item.ValueCopy(nil)
			if err != nil {
				return err
			}

			payload := k[len(database.PrefixResults):]
			key := binary.BigEndian.Uint64(payload)

			var scores [7]int8
			buf := bytes.NewBuffer(v)
			if err := gob.NewDecoder(buf).Decode(&scores); err != nil {
				return err
			}

			fmt.Fprintf(f, "\t%d: {", key)
			for i, s := range scores {
				fmt.Fprintf(f, "%d", s)
				if i < 6 {
					fmt.Fprint(f, ", ")
				}
			}
			fmt.Fprintln(f, "},")
		}
		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

	fmt.Fprintln(f, "}")
}
